# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "fluxbot-studio-ia"
handle = "fluxbot-studio-ia"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/auth/callback",
  "https://shopify.dev/apps/default-app-home/auth/shopify/callback",
  "https://shopify.dev/apps/default-app-home/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
