# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e33f15eca7b32e62ea7137311172df5"
name = "fluxbot-studio-ia"
handle = "fluxbot-studio-ia"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c8cc9986.myshopify.com"
include_config_on_deploy = true

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = ["https://example.com/auth/callback"]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
