name = "React Router"
roles = ["frontend", "backend"]
api_version = "2026-01"
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate --schema ../../infra/prisma/schema.prisma"
dev = "npx prisma migrate deploy --schema ../../infra/prisma/schema.prisma && npx react-router dev --host"
build = "npm run build"
start = "npm run start"
