# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c36112e98ce36be869eb0dc5efdd572"
name = "fluxbot-studio"
application_url = "https://fluxbot-studio.example.com"
embedded = true
handle = "fluxbot-studio"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-c8cc9986.myshopify.com"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_customers,read_content,read_locales,read_online_store_pages,read_themes"

[app_proxy]
url = "https://fluxbot-studio.example.com"
subpath = "fluxbot"
prefix = "apps"

[auth]
redirect_urls = [
  "https://fluxbot-studio.example.com/auth/callback",
  "https://fluxbot-studio.example.com/auth/shopify/callback",
  "https://fluxbot-studio.example.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
path = "extensions/chat-widget"
