name = "React Router"
roles = ["frontend", "backend"]
api_version = "2026-01"
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "../../node_modules/.bin/prisma generate --schema ../../infra/prisma/schema.prisma"
dev = "../../node_modules/.bin/prisma migrate deploy --schema ../../infra/prisma/schema.prisma && ../../node_modules/.bin/react-router dev --host"
build = "npm run build"
start = "npm run start"
